<!--
SPDX-FileCopyrightText: 2022 smdn <smdn@smdn.jp>
SPDX-License-Identifier: MIT
-->
<Project>
  <PropertyGroup>
    <!-- enable target framework net*.0 (.NET >= 5.0) by default -->
    <EnableTargetFrameworkDotNet>true</EnableTargetFrameworkDotNet>
    <EnableTargetFrameworkDotNet100>true</EnableTargetFrameworkDotNet100>
    <EnableTargetFrameworkDotNet80>true</EnableTargetFrameworkDotNet80>
    <!-- disable target framework net4xy (.NET Framework/Mono) by default -->
    <EnableTargetFrameworkNetFx>false</EnableTargetFrameworkNetFx>
    <!-- enable target framework net4xy (.NET Framework) on Windows -->
    <EnableTargetFrameworkNetFx
      Condition="$([MSBuild]::IsOSPlatform('Windows'))"
    >true</EnableTargetFrameworkNetFx>
  </PropertyGroup>
</Project>
